# Generated by Django 3.2.8 on 2022-03-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.TextField()),
                ('productDescription', models.TextField()),
                ('code', models.TextField()),
                ('QRcodePicture', models.ImageField(blank=True, upload_to='QRcode')),
                ('image', models.ImageField(upload_to='product')),
                ('manufacturer', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='transactionsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.CharField(max_length=100)),
                ('tx_hash', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
