# Generated by Django 4.0.3 on 2022-03-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.TextField()),
                ('productDescription', models.TextField()),
                ('code', models.TextField()),
                ('QRcodePicture', models.ImageField(blank=True, upload_to='QRcode')),
                ('image', models.ImageField(upload_to='product')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
